version: "3.8"

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=
      - MONGO_INITDB_ROOT_PASSWORD=
    depends_on:
      - db
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      # Username for the mongo database
      - MONGO_INITDB_ROOT_USERNAME=
      # Password for the mongo database
      - MONGO_INITDB_ROOT_PASSWORD=
    volumes:
      - todo_db:/data/db
volumes:
  todo_db:
